# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master , ci ]
  pull_request:
    branches: [ master , ci ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Get yq
      #- name: yq - portable yaml processor
      #  uses: mikefarah/yq@v4.9.6

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Install lua
        run: |
          sudo apt-get install build-essential libreadline-dev
          curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz
          tar -zxf lua-5.3.5.tar.gz
          cd lua-5.3.5
          make linux test
          sudo make install

      - name: Install luarocks
        run: |
          wget https://luarocks.org/releases/luarocks-3.3.1.tar.gz
          tar zxpf luarocks-3.3.1.tar.gz
          cd luarocks-3.3.1    
          ./configure --with-lua-include=/usr/local/include
          make
          sudo make install
          
      - name: Check for lua
        run: |
          lua -v
      
      - run: ./scripts/autogen 

      - run: ./configure

      - run: make
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
